/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Apr 11 10:04:33 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.bbs.domain.model;

import java.io.Serializable;
import java.util.*;
/**
 * A class that represents a row in the subject table. 
 * You can customize the behavior of this class by editing the class, {@link Subject()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractSubject 
    extends com.bbs.domain.model.BaseObject
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long id;

    /** The value of the simple name property. */
    private java.lang.String name;

    /** The value of the simple description property. */
    private java.lang.String description;

    /** The value of the simple createdate property. */
    private java.util.Date createdate;

    /** The value of the simple photo property. */
    private java.lang.String photo;

    /** The value of the simple status property. */
    private java.lang.String status;

    private Set topics = new HashSet();
    /**
     * Simple constructor of AbstractSubject instances.
     */
    public AbstractSubject()
    {
    }

    /**
     * Constructor of AbstractSubject instances given a simple primary key.
     * @param id
     */
    public AbstractSubject(java.lang.Long id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Long id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the name column.
     * @return java.lang.String
     */
    public java.lang.String getName()
    {
        return this.name;
    }

    /**
     * Set the value of the name column.
     * @param name
     */
    public void setName(java.lang.String name)
    {
        this.name = name;
    }

    /**
     * Return the value of the description column.
     * @return java.lang.String
     */
    public java.lang.String getDescription()
    {
        return this.description;
    }

    /**
     * Set the value of the description column.
     * @param description
     */
    public void setDescription(java.lang.String description)
    {
        this.description = description;
    }

    /**
     * Return the value of the createdate column.
     * @return java.util.Date
     */
    public java.util.Date getCreatedate()
    {
        return this.createdate;
    }

    /**
     * Set the value of the createdate column.
     * @param createdate
     */
    public void setCreatedate(java.util.Date createdate)
    {
        this.createdate = createdate;
    }

    /**
     * Return the value of the photo column.
     * @return java.lang.String
     */
    public java.lang.String getPhoto()
    {
        return this.photo;
    }

    /**
     * Set the value of the photo column.
     * @param photo
     */
    public void setPhoto(java.lang.String photo)
    {
        this.photo = photo;
    }

    /**
     * Return the value of the status column.
     * @return java.lang.String
     */
    public java.lang.String getStatus()
    {
        return this.status;
    }

    /**
     * Set the value of the status column.
     * @param status
     */
    public void setStatus(java.lang.String status)
    {
        this.status = status;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Subject))
            return false;
        Subject that = (Subject) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	public Set getTopics() {
		return topics;
	}

	public void setTopics(Set topics) {
		this.topics = topics;
	}
}
