/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Apr 19 17:08:08 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.bbs.domain.model;

import java.io.Serializable;
import java.util.*;
/**
 * A class that represents a row in the topic table. 
 * You can customize the behavior of this class by editing the class, {@link Topic()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractTopic 
    extends com.bbs.domain.model.BaseObject
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long id;

    /** The value of the simple title property. */
    private java.lang.String title;

    /** The value of the simple content property. */
    private java.lang.String content;

    /** The value of the simple createdate property. */
    private java.util.Date createdate;

    /** The value of the simple writer property. */

    /** The value of the simple subjectid property. */

    /** The value of the simple iflocked property. */
    private java.lang.String iflocked;

    /** The value of the simple lastmodiedtime property. */
    private java.util.Date lastmodiedtime;

    /**
     * Simple constructor of AbstractTopic instances.
     */
    
    private User writer;
    private Subject subject;
    private Set responses = new HashSet();
    public AbstractTopic()
    {
    }

    /**
     * Constructor of AbstractTopic instances given a simple primary key.
     * @param id
     */
    public AbstractTopic(java.lang.Long id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Long id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the title column.
     * @return java.lang.String
     */
    public java.lang.String getTitle()
    {
        return this.title;
    }

    /**
     * Set the value of the title column.
     * @param title
     */
    public void setTitle(java.lang.String title)
    {
        this.title = title;
    }

    /**
     * Return the value of the content column.
     * @return java.lang.String
     */
    public java.lang.String getContent()
    {
        return this.content;
    }

    /**
     * Set the value of the content column.
     * @param content
     */
    public void setContent(java.lang.String content)
    {
        this.content = content;
    }

    /**
     * Return the value of the createdate column.
     * @return java.util.Date
     */
    public java.util.Date getCreatedate()
    {
        return this.createdate;
    }

    /**
     * Set the value of the createdate column.
     * @param createdate
     */
    public void setCreatedate(java.util.Date createdate)
    {
        this.createdate = createdate;
    }

    /**
     * Return the value of the writer column.
     * @return java.lang.Long
     */
   
    /**
     * Return the value of the iflocked column.
     * @return java.lang.String
     */
    public java.lang.String getIflocked()
    {
        return this.iflocked;
    }

    /**
     * Set the value of the iflocked column.
     * @param iflocked
     */
    public void setIflocked(java.lang.String iflocked)
    {
        this.iflocked = iflocked;
    }

    /**
     * Return the value of the lastmodiedtime column.
     * @return java.util.Date
     */
    public java.util.Date getLastmodiedtime()
    {
        return this.lastmodiedtime;
    }

    /**
     * Set the value of the lastmodiedtime column.
     * @param lastmodiedtime
     */
    public void setLastmodiedtime(java.util.Date lastmodiedtime)
    {
        this.lastmodiedtime = lastmodiedtime;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Topic))
            return false;
        Topic that = (Topic) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	public Set getResponses() {
		return responses;
	}

	public void setResponses(Set responses) {
		this.responses = responses;
	}

	public Subject getSubject() {
		return subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public User getWriter() {
		return writer;
	}

	public void setWriter(User writer) {
		this.writer = writer;
	}
}
