/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Apr 10 21:02:56 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.bbs.domain.model;

import java.io.Serializable;
import java.util.*;
/**
 * A class that represents a row in the user table. 
 * You can customize the behavior of this class by editing the class, {@link User()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractUser 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long id;

    /** The value of the simple username property. */
    private java.lang.String username;

    /** The value of the simple pwd property. */
    private java.lang.String pwd;

    /** The value of the simple nickname property. */
    private java.lang.String nickname;

    /** The value of the simple sex property. */
    private java.lang.String sex;

    /** The value of the simple birthday property. */
    private java.lang.String birthday;

    /** The value of the simple email property. */
    private java.lang.String email;

    /** The value of the simple phone property. */
    private java.lang.String phone;

    /** The value of the simple description property. */
    private java.lang.String description;

    /** The value of the simple count property. */
    private java.lang.Integer count;

    /** The value of the simple status property. */
    private java.lang.String status;

    /** The value of the simple registerdate property. */
    private java.util.Date registerdate;
   
    private java.lang.String role;
    
    private Set topic;
    private Set responses;
    
    /**
     * Simple constructor of AbstractUser instances.
     */
    public AbstractUser()
    {
    }

    /**
     * Constructor of AbstractUser instances given a simple primary key.
     * @param id
     */
    public AbstractUser(java.lang.Long id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Long id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the username column.
     * @return java.lang.String
     */
    public java.lang.String getUsername()
    {
        return this.username;
    }

    /**
     * Set the value of the username column.
     * @param username
     */
    public void setUsername(java.lang.String username)
    {
        this.username = username;
    }

    /**
     * Return the value of the pwd column.
     * @return java.lang.String
     */
    public java.lang.String getPwd()
    {
        return this.pwd;
    }

    /**
     * Set the value of the pwd column.
     * @param pwd
     */
    public void setPwd(java.lang.String pwd)
    {
        this.pwd = pwd;
    }

    /**
     * Return the value of the nickname column.
     * @return java.lang.String
     */
    public java.lang.String getNickname()
    {
        return this.nickname;
    }

    /**
     * Set the value of the nickname column.
     * @param nickname
     */
    public void setNickname(java.lang.String nickname)
    {
        this.nickname = nickname;
    }

    /**
     * Return the value of the sex column.
     * @return java.lang.String
     */
    public java.lang.String getSex()
    {
        return this.sex;
    }

    /**
     * Set the value of the sex column.
     * @param sex
     */
    public void setSex(java.lang.String sex)
    {
        this.sex = sex;
    }

    /**
     * Return the value of the birthday column.
     * @return java.util.Date
     */
    public java.lang.String getBirthday()
    {
        return this.birthday;
    }

    /**
     * Set the value of the birthday column.
     * @param birthday
     */
    public void setBirthday(java.lang.String birthday)
    {
        this.birthday = birthday;
    }

    /**
     * Return the value of the email column.
     * @return java.lang.String
     */
    public java.lang.String getEmail()
    {
        return this.email;
    }

    /**
     * Set the value of the email column.
     * @param email
     */
    public void setEmail(java.lang.String email)
    {
        this.email = email;
    }

    /**
     * Return the value of the phone column.
     * @return java.lang.String
     */
    public java.lang.String getPhone()
    {
        return this.phone;
    }

    /**
     * Set the value of the phone column.
     * @param phone
     */
    public void setPhone(java.lang.String phone)
    {
        this.phone = phone;
    }

    /**
     * Return the value of the description column.
     * @return java.lang.String
     */
    public java.lang.String getDescription()
    {
        return this.description;
    }

    /**
     * Set the value of the description column.
     * @param description
     */
    public void setDescription(java.lang.String description)
    {
        this.description = description;
    }

    /**
     * Return the value of the count column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getCount()
    {
        return this.count;
    }

    /**
     * Set the value of the count column.
     * @param count
     */
    public void setCount(java.lang.Integer count)
    {
        this.count = count;
    }

    /**
     * Return the value of the status column.
     * @return java.lang.String
     */
    public java.lang.String getStatus()
    {
        return this.status;
    }

    /**
     * Set the value of the status column.
     * @param status
     */
    public void setStatus(java.lang.String status)
    {
        this.status = status;
    }

    /**
     * Return the value of the registerdate column.
     * @return java.util.Date
     */
    public java.util.Date getRegisterdate()
    {
        return this.registerdate;
    }

    /**
     * Set the value of the registerdate column.
     * @param registerdate
     */
    public void setRegisterdate(java.util.Date registerdate)
    {
        this.registerdate = registerdate;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof User))
            return false;
        User that = (User) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	public Set getResponses() {
		return responses;
	}

	public void setResponses(Set responses) {
		this.responses = responses;
	}

	public Set getTopic() {
		return topic;
	}

	public void setTopic(Set topic) {
		this.topic = topic;
	}

	public java.lang.String getRole() {
		return role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}
}
